# Generated by Django 5.0.6 on 2024-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadores',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_jogadores'),
        ),
    ]
