# Generated by Django 5.0.6 on 2024-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0002_jogadores_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadores',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
