# Generated by Django 5.0.6 on 2024-07-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0004_clube_remove_jogadores_time_jogadores_clube'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_clubes'),
        ),
    ]
